### ISSUE TITLE
No asset on release 0.5

### ISSUE THREAD

**Issue by ostcar** [lukewilliamboswell/roc-ansi#7]
In the 0.5 release, the bundled package is missing:

https://github.com/lukewilliamboswell/roc-ansi/releases/tag/0.5

**Comment by lukewilliamboswell** [comment]
Interesting, I'll need to investigate why the action didn't run.

**Comment by lukewilliamboswell** [comment]
It's there now. Just needed the updated nightly as I made the PR before the new changes landed. Thank you for raising the issue.
